name: riverpod_navigator
description: Simple but powerfull Flutter navigation with riverpod and Navigator 2.0
version: 1.0.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_spinkit: ^5.1.0

  hooks_riverpod: ^1.0.0
  meta: ^1.7.0
  riverpod_navigator_core: # 1.0.0
    path: ../riverpod_navigator_core 

dev_dependencies: 
  test:
  
flutter:
  uses-material-design: true
